### ISSUE TITLE
Incompatibility with CofhCore

### ISSUE THREAD

**Issue by Dr-WeiAL** [GekidoLukas/weaponleveling#5] opened 2022-09-07 12:26 UTC
**Describe the bug**
1.The latest version does not have Simplified Chinese
2.Bow upgrade did not increase shooting damage but increased melee damage

**Mod/Minecraft Version**
Minecraft Version:1.18.2
Mod Version:1.2.2

**To Reproduce**
1. upgrade bow

**Expected behavior**
fix it?

**Screenshots**
![image](https://user-images.githubusercontent.com/47446553/188877802-6a38bf39-4b5a-4f53-b57a-31b6aa5babbe.png)
![image](https://user-images.githubusercontent.com/47446553/188877857-142d1be9-4102-484f-beba-49bea000346b.png)
![image](https://user-images.githubusercontent.com/47446553/188877921-6e74bf7e-e92b-4096-87c5-0a1142482f86.png)

**Additional context**

**Comment by GekidoLukas** [comment] 2022-09-13 23:15
Hello, so I fixed the issue with the melee damage being applied, but I do not seem to be able to reproduce the steps to not have projectile damage. What other mods do you use?

**Comment by Dr-WeiAL** [comment] 2022-09-14 16:44
Regarding the problem of not increasing the projectile damage, I checked the mod and found that the projectile damage is normal after removing the cofh

**Comment by GekidoLukas** [comment] 2022-09-14 20:21
Hmm, well that is interesting, I will add this to incompatible mods list until I have found a solution for that

**Comment by GekidoLukas** [comment] 2022-09-23 15:54
I have chatted with the developer of cofh, and they said, that they will probably rework some of their code to work with the way of changing the projectile damage I am using. This will however take some time.
That means, a future update of cofh core will fix the issue.
I will not close this issue yet, because atm the issue is not resolved.

**Closed as completed** 2023-12-19 21:47 UTC
Labels: bug, Upcoming fix
