### ISSUE TITLE
Latest version crashing game and launcher

### ISSUE THREAD

**Issue by Hir0shiyt** [GekidoLukas/weaponleveling#9] opened 2022-09-29 22:59 UTC
**Describe the bug**
When i click on the play button in the launcher, it closes and wont let me open it back again.

**Mod/Minecraft Version**
Minecraft Version: Forge 40.1.80 - 1.18.2
Mod Version: 1.18.2 - 1.3

**To Reproduce**
1. Click play
2. Game crashes
3. Launcher closes

**Expected behavior**
Maybe an incompatibility with another mod

**Screenshots**
I can't make screenshots of a crash

**Additional context**
Here's the log: https://pastebin.com/zYKvZiEK

**Comment by GekidoLukas** [comment] 2022-10-01 05:59
Hello, could you please see which mod causes the issue? You seem to have many installed.

**Comment by Hir0shiyt** [comment] 2022-10-01 15:12
> Hello, could you please see which mod causes the issue? You seem to have many installed.

I have my eyes on magnesium/sodium, since it changes most of the code

**Comment by GekidoLukas** [comment] 2022-10-01 17:33
In my testing, sodium and magnesium worked fine. I don't change the rendering engine in any way, It is probably a mod, that uses similar mixins to what I do.

**Comment by Hir0shiyt** [comment] 2022-10-01 17:34
> In my testing, sodium and magnesium worked fine. I don't change the rendering engine in any way, It is probably a mod, that uses similar mixins to what I do.

I'll send you my mod list later, its 100+ mods tho

**Comment by PhweeDev** [comment] 2022-10-01 21:40
I tested it with ONLY weaponleveling 1.18.2-1.3.1. It crashes on start-up.

**Comment by FoggyWizard** [comment] 2022-10-02 01:42
Confirmed for 1.18.2-1.3.1 Forge. No crash log attached. It crashes both game and launcher before it can even register that its crashing.

**Comment by Hir0shiyt** [comment] 2022-10-02 03:58
> Confirmed for 1.18.2-1.3.1 Forge. No crash log attached. It crashes both game and launcher before it can even register that its crashing.

You described it as right as it can be

**Comment by GekidoLukas** [comment] 2022-10-02 14:09
> I tested it with ONLY weaponleveling 1.18.2-1.3.1. It crashes on start-up.

That is very odd. Maybe it is an issue with forge or fabric. Could you provide me with your forge Version and also your logs and debug logs?

**Comment by GekidoLukas** [comment] 2022-10-02 14:09
> Confirmed for 1.18.2-1.3.1 Forge. No crash log attached. It crashes both game and launcher before it can even register that its crashing.

What forge Version are you using?

**Comment by Hir0shiyt** [comment] 2022-10-02 14:16
> > Confirmed for 1.18.2-1.3.1 Forge. No crash log attached. It crashes both game and launcher before it can even register that its crashing.
> 
> What forge Version are you using?

I'm using the latest forge version for 1.18.2

**Comment by FoggyWizard** [comment] 2022-10-02 18:42
> 

Forge 40.1.80, the most updated for 1.18.2, iirc

**Comment by AbieTheFishman** [comment] 2022-10-03 01:34
Experiencing same issue

**Comment by AbieTheFishman** [comment] 2022-10-03 01:38
weaponleveling-1.18.2-1.3.jar is working
forge version 40.180

**Comment by GekidoLukas** [comment] 2022-10-04 00:49
I uploaded a new File to curseforge, please tell me, if it still crashes

**Comment by PhweeDev** [comment] 2022-10-04 14:46
Tested by itself. Works as of 1.3.4.

**Comment by GekidoLukas** [comment] 2022-10-04 14:54
Good, I will close this issue now (finally 😅)
It has been a weird fix

**Closed as completed by GekidoLukas** 2022-10-04 14:54 UTC
Labels: bug

**Comment by FoggyWizard** [comment] 2022-10-04 15:47
Still happening for me with 1.3.4, but since I'm running a good 500 mods I'm not expecting anyone to be able to pin down which one is causing an incompatibility. 1.2.3 still works wonders for me. Anyone have a config file of the built-in compatibilities 1.3.x of this mod has?

**Comment by Hir0shiyt** [comment] 2022-10-04 17:18
> 

How good has your pc to be to run 500+ mods

**Comment by Hir0shiyt** [comment] 2022-10-04 17:36
> Good, I will close this issue now (finally 😅) It has been a weird fix

It still crashes and i got the log:

[latest.log](https://github.com/GeradesoLukas/weaponleveling/files/9709364/latest.log)

**Comment by FoggyWizard** [comment] 2022-10-04 20:24
> > 
> 
> How good has your pc to be to run 500+ mods

Top of the line back in 2016, but it's more a matter of not going overboard on graphics (I'm keeping to 16p textures and the most lightweight shaders I could find and still have the clear water I wanted, running the shader at minimal settings as well) and understanding how each mod is going to interact when you add them, as well as engine limitations. There's normally not much of an issue with fps at all, but I expect it would be very different if I were trying to run a server. There is, however, a bit of hanging whenever you batch-craft items or when you walk too far from your 'home' where you logged in at, as well as occasional failure for blocks to be updated when interacting with them. I consider these to be acceptable losses and limitations, others wouldn't. Unfortunately, with this many mods, it makes it exceptionally hard to pinpoint interaction issues that occur specifically when a mod updates, since you only have one half of the story.

**Comment by Hir0shiyt** [comment] 2022-10-04 21:59
> > > 
> > 
> > 
> > How good has your pc to be to run 500+ mods
> 
> Top of the line back in 2016, but it's more a matter of not going overboard on graphics (I'm keeping to 16p textures and the most lightweight shaders I could find and still have the clear water I wanted, running the shader at minimal settings as well) and understanding how each mod is going to interact when you add them, as well as engine limitations. There's normally not much of an issue with fps at all, but I expect it would be very different if I were trying to run a server. There is, however, a bit of hanging whenever you batch-craft items or when you walk too far from your 'home' where you logged in at, as well as occasional failure for blocks to be updated when interacting with them. I consider these to be acceptable losses and limitations, others wouldn't. Unfortunately, with this many mods, it makes it exceptionally hard to pinpoint interaction issues that occur specifically when a mod updates, since you only have one half of the story.

Now that you point it out, it kinda makes more sense for me now
