### ISSUE TITLE
Item-Stacking issue again present

### ISSUE THREAD

**Issue by Moomsy** [GekidoLukas/weaponleveling#22] opened 2022-11-02 10:46 UTC
**Describe the bug**

The known problem that broken items and items from inventories and Storage containers will not stack properly because of empty Tags given to them is again present in the most recent Version (1.18.2 - 1.4.1)

**Mod/Minecraft Version**
Minecraft Version: 1.18.2
Mod Version: 1.4.1

**To Reproduce**
1. Take any Stack of placeable Item
2. Place Block from that Stack / Break Block in-world that matches the Stacked Item
3. Collect item
4. Item will not Stack

**Expected behavior**
Items should be supposed to be stackable if the item exactly matches the one in the players Inventory

**Additional context**
The Problem seemed fixed in Version 1.4.0 but in 1.4.1 items behave the way they did pre-1.4.0 , meaning : not Stacking correctly

Sometimes do not even show an empty Tag and still do not Stack , i am running a 325Mods-Modpack with many custom configs, removing Weaponleveling does fix this problem Immediatly - BUT - it is an important part of the Pack so i hope the culprit why exactly it applies those Tags in the first place can be narrowed down and be fixed.
![Bild_2022-11-02_115216094](https://user-images.githubusercontent.com/88433286/199471559-bfcc66fc-b423-431b-9971-9e91e6c23921.png)
![Bild_2022-11-02_115233118](https://user-images.githubusercontent.com/88433286/199471624-b73798e1-5cfd-4ff7-97cb-956ec811bf6b.png)

**Comment by GekidoLukas** [comment] 2022-11-02 14:17
Huh, interesting, I did not manage to reproduce that.
1.4.1 does not change the system at all compared to 1.4.0. Could you check, if another mod might cause this? Using just weapon leveling, it stayed stackable, even after breaking, placing etc.

**Comment by GekidoLukas** [comment] 2023-12-19 21:48
This is an issue, that many mods cause due to using a method that creates empty tags. This is resolved in my mod now. Other mods have to do it themselves.

**Closed as completed by GekidoLukas** 2023-12-19 21:48 UTC
Labels: bug, requires info
