### ISSUE TITLE
Hitting mobs crashes game

### ISSUE THREAD

**Issue by tehehe22** [GekidoLukas/weaponleveling#35] opened 2023-01-29 01:52 UTC
Anytime I hit a mob the game crashes for no reason, weapon or no weapon

1.18.2
fabric 1.4.2

Here is the log:

The game crashed whilst exception in server tick loop
Error: org.spongepowered.asm.mixin.injection.throwables.InjectionError: LVT in net/minecraft/class_1657::method_7324(Lnet/minecraft/class_1297;)V has incompatible changes at opcode 905 in callback weaponleveling.mixins.json:MixinPlayer from mod weaponleveling->@Inject::injectedDamage(Lnet/minecraft/class_1297;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;FFFZZIZZDFZIZLnet/minecraft/class_1799;Lnet/minecraft/class_1297;)V.

**Comment by tehehe22** [comment] 2023-01-29 01:58
Also the game does not like when I remove weaponleveling as it won't let me load into any world

**Comment by GekidoLukas** [comment] 2023-12-19 21:54
I cannot reproduce this issue. Since this does not happen now I will close this issue

**Closed as completed by GekidoLukas** 2023-12-19 21:54 UTC
Labels: bug
